### PR TITLE
Quickhull

### PR DESCRIPTION
**Pull request by athas**
Only has the Futhark part right now, because I'm not sure I will have time to finish the SML or hybrid one today.  Depends on #3.

### CODE REVIEW

**Comment by shwestrick** [comment]
Cool! Want to go ahead and merge? Or is there a bit more you want to do first?

for CPU, we have a MPL implementation that could be used: https://github.com/MPLLang/parallel-ml-bench/blob/main/mpl/bench/quickhull/Quickhull.sml

**Comment by athas** [comment]
It's not useful right now; let's not merge until I have copied over your SML implementation.  (It was always my intention just to glue existing code together.)

**Comment by athas** [comment]
I did some more work on this one.

1. The pure GPU and SML implementations both work and agree on their results (up to minor floating point jitter).
2. The hybrid implementation is quite naive, and also does not produce the right results.  My idea was to implement the semihull parts on the GPU, but I must have gotten something wrong.
3. It needs better input generation - currently the points are uniformly distributed in the unit square, making for a very boring hull.  In particular, the recursive subproblems tend to quickly become very very small, which makes load balancing and GPU offloading less interesting.

**Comment by shwestrick** [comment]
IIRC, for performance, the cost of quickhull is usually dominated by the "top-level" split, specifically [these lines](https://github.com/MPLLang/parallel-ml-bench/blob/5b9aab5f345c9488ceec2728280a4a11205f4af8/mpl/bench/quickhull/Quickhull.sml#L72-L97), and the cost of the semihull calculations is fairly small in comparison. (Though, it's been a while... we should put some timings in to check.)

It would be interesting to look at other input distributions, though. Perhaps a different input would be easier to hybridize, as the semihulls might be more computationally intensive.

Happy to help out wherever needed -- just let me know!

**Comment by athas** [comment]
If you have interesting point generators lying around, feel free to add them.  I'll try to think of more interesting ways to hybridize the algorithm.  All this just makes quickhull an even more interesting case study.

**Comment by shwestrick** [comment]
> If you have interesting point generators lying around, feel free to add them.

Sounds good, happy to do this. In the past I've used the PBBS point generators and these can be fairly interesting. I'll add those when I get the chance.

> I'll try to think of more interesting ways to hybridize the algorithm. All this just makes quickhull an even more interesting case study.

Great, looking forward to discussing at our meeting.

**Comment by athas** [comment]
I get these timings from the (original, C++) PBBS implementation on a 96-core machine; from what I remember MPL is pretty close:

```
2DinSphere_100000000 :  -r 1 -o /tmp/ofile945503_588762 : '0.184', geomean = 0.184
2Dkuzmin_100000000 :  -r 1 -o /tmp/ofile291948_183926 : '0.065', geomean = 0.065
2DonSphere_100000000 :  -r 1 -o /tmp/ofile712632_237053 : '3.505', geomean = 3.505
```

The Futhark runtimes on an A100 on the same machine with the same datasets are this:

```
data/2DinSphere_100M.in:      36465μs (95% CI: [   36446.9,    36483.0])
data/2Dkuzmin_100M.in:        21485μs (95% CI: [   21476.9,    21492.8])
data/2DonSphere_100M.in:     208695μs (95% CI: [  208259.5,   209153.1])
```

It is interesting that performance varies from Futhark being only slightly faster to being *much* faster (and there are probably cases where Futhark is slower, although I couldn't remember how to generate new datasets for PBBS).  I think the ideal case for this benchmark is to come up with datasets that require different scheduling behaviour, and these runtimes suggest that it *might* be possible.

Another thing: while it has its charm to work on a branch of a branch of a branch of the main branch of a fork of a repository that is not actually related to what we are doing, perhaps it might be a good idea to give this work a repository of its own?

**Comment by athas** [comment]
Now produces the right result, although the points are not in clockwise order (or whatever it is the MPL implementation produces).

**Comment by shwestrick** [comment]
> Now produces the right result, although the points are not in clockwise order (or whatever it is the MPL implementation produces).

Great! Not sure if the order matters, as long as the hull matches.

> perhaps it might be a good idea to give this work a repository of its own?

Yes, I've been thinking the same. I'll make a repo in [MPLLang](https://github.com/MPLLang) for it?

**Comment by athas** [comment]
> Yes, I've been thinking the same. I'll make a repo in [MPLLang](https://github.com/MPLLang) for it?

Good idea.

**Comment by shwestrick** [comment]
Going to merge this now and migrate to new repository, I'll let you know when the new repo is up-and-running (probably within the next 30 mins or so)

**Pull request merged**
